### ISSUE TITLE
[directional sensor] __sensor__/control.lua:136: attempt to index local 'sensor' (a nil value)

### ISSUE THREAD

**Issue by jaguilar** [Kikkers/Factorio-Smarter-Circuitry#4]
From today's master of this mod.

Factorio 0.12.4, 0.12.6 64-bit
Windows 10
Reproduces 100% of the time with this save file: https://drive.google.com/file/d/0B_bJrdrwGYeWYTAxZ2dIZzg0S0k/view?usp=sharing

Repro instructions:
1. Load game.
2. Wait.

If you walk over to where my directional sensor is located, it's directly to the west of your starting position, near the bank of power plants. The issue seems to occur when the network runs fully out of power (perhaps due to the biter attack from the south)?

**Comment by jaguilar** [comment]
I'm guessing the issue is the no-arg call to tick_clear() here: https://github.com/Kikkers/Factorio-Smarter-Circuitry/blob/master/sensor_0.4.7/control.lua#L112. That matches my experience with it happening when the power runs out. I'll see if I can fix the problem locally and see if it recurs.

**Comment by jaguilar** [comment]
Yep. That seemed to do it. I'll send you a pull request.

**Comment by Kikkers** [comment]
Thanks, I haven't been able to do proper tests with the latest commit.
